// <auto-generated />
namespace Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _20180417NUEVOMODULOPERMISODEVISUALIZACION : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20180417NUEVOMODULOPERMISODEVISUALIZACION));
        
        string IMigrationMetadata.Id
        {
            get { return "201804171856304_20180417NUEVOMODULOPERMISODEVISUALIZACION"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
