//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 16/04/2018 18:55:06
namespace MSS_REPORTES.services.ventas.ventasServices
{
    
    /// <summary>
    /// There are no comments for ventasServices in the schema.
    /// </summary>
    public partial class ventasServices : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new ventasServices object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ventasServices(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for ventas in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ventasType> ventas
        {
            get
            {
                if ((this._ventas == null))
                {
                    this._ventas = base.CreateQuery<ventasType>("ventas");
                }
                return this._ventas;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ventasType> _ventas;
        /// <summary>
        /// There are no comments for ventasSoles in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ventasSolesType> ventasSoles
        {
            get
            {
                if ((this._ventasSoles == null))
                {
                    this._ventasSoles = base.CreateQuery<ventasSolesType>("ventasSoles");
                }
                return this._ventasSoles;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ventasSolesType> _ventasSoles;
        /// <summary>
        /// There are no comments for vendedores in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<vendedoresType> vendedores
        {
            get
            {
                if ((this._vendedores == null))
                {
                    this._vendedores = base.CreateQuery<vendedoresType>("vendedores");
                }
                return this._vendedores;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<vendedoresType> _vendedores;
        /// <summary>
        /// There are no comments for articulo in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<articuloType> articulo
        {
            get
            {
                if ((this._articulo == null))
                {
                    this._articulo = base.CreateQuery<articuloType>("articulo");
                }
                return this._articulo;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<articuloType> _articulo;
        /// <summary>
        /// There are no comments for cliente in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<clienteType> cliente
        {
            get
            {
                if ((this._cliente == null))
                {
                    this._cliente = base.CreateQuery<clienteType>("cliente");
                }
                return this._cliente;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<clienteType> _cliente;
        /// <summary>
        /// There are no comments for ventas in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToventas(ventasType ventasType)
        {
            base.AddObject("ventas", ventasType);
        }
        /// <summary>
        /// There are no comments for ventasSoles in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToventasSoles(ventasSolesType ventasSolesType)
        {
            base.AddObject("ventasSoles", ventasSolesType);
        }
        /// <summary>
        /// There are no comments for vendedores in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddTovendedores(vendedoresType vendedoresType)
        {
            base.AddObject("vendedores", vendedoresType);
        }
        /// <summary>
        /// There are no comments for articulo in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToarticulo(articuloType articuloType)
        {
            base.AddObject("articulo", articuloType);
        }
        /// <summary>
        /// There are no comments for cliente in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddTocliente(clienteType clienteType)
        {
            base.AddObject("cliente", clienteType);
        }
    }
    /// <summary>
    /// There are no comments for MSS_REPORTES.services.ventas.ventasServices.ventasType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// DocEntry
    /// LineNum
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("ventas")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("DocEntry", "LineNum")]
    public partial class ventasType : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ventasType object.
        /// </summary>
        /// <param name="docEntry">Initial value of DocEntry.</param>
        /// <param name="lineNum">Initial value of LineNum.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ventasType CreateventasType(int docEntry, int lineNum)
        {
            ventasType ventasType = new ventasType();
            ventasType.DocEntry = docEntry;
            ventasType.LineNum = lineNum;
            return ventasType;
        }
        /// <summary>
        /// There are no comments for Property DocEntry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int DocEntry
        {
            get
            {
                return this._DocEntry;
            }
            set
            {
                this.OnDocEntryChanging(value);
                this._DocEntry = value;
                this.OnDocEntryChanged();
                this.OnPropertyChanged("DocEntry");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _DocEntry;
        partial void OnDocEntryChanging(int value);
        partial void OnDocEntryChanged();
        /// <summary>
        /// There are no comments for Property DocNum in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> DocNum
        {
            get
            {
                return this._DocNum;
            }
            set
            {
                this.OnDocNumChanging(value);
                this._DocNum = value;
                this.OnDocNumChanged();
                this.OnPropertyChanged("DocNum");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _DocNum;
        partial void OnDocNumChanging(global::System.Nullable<int> value);
        partial void OnDocNumChanged();
        /// <summary>
        /// There are no comments for Property LineNum in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int LineNum
        {
            get
            {
                return this._LineNum;
            }
            set
            {
                this.OnLineNumChanging(value);
                this._LineNum = value;
                this.OnLineNumChanged();
                this.OnPropertyChanged("LineNum");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _LineNum;
        partial void OnLineNumChanging(int value);
        partial void OnLineNumChanged();
        /// <summary>
        /// There are no comments for Property CardCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CardCode
        {
            get
            {
                return this._CardCode;
            }
            set
            {
                this.OnCardCodeChanging(value);
                this._CardCode = value;
                this.OnCardCodeChanged();
                this.OnPropertyChanged("CardCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CardCode;
        partial void OnCardCodeChanging(string value);
        partial void OnCardCodeChanged();
        /// <summary>
        /// There are no comments for Property CardName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CardName
        {
            get
            {
                return this._CardName;
            }
            set
            {
                this.OnCardNameChanging(value);
                this._CardName = value;
                this.OnCardNameChanged();
                this.OnPropertyChanged("CardName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CardName;
        partial void OnCardNameChanging(string value);
        partial void OnCardNameChanged();
        /// <summary>
        /// There are no comments for Property Sucursal in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Sucursal
        {
            get
            {
                return this._Sucursal;
            }
            set
            {
                this.OnSucursalChanging(value);
                this._Sucursal = value;
                this.OnSucursalChanged();
                this.OnPropertyChanged("Sucursal");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Sucursal;
        partial void OnSucursalChanging(string value);
        partial void OnSucursalChanged();
        /// <summary>
        /// There are no comments for Property Fecha in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> Fecha
        {
            get
            {
                return this._Fecha;
            }
            set
            {
                this.OnFechaChanging(value);
                this._Fecha = value;
                this.OnFechaChanged();
                this.OnPropertyChanged("Fecha");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _Fecha;
        partial void OnFechaChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnFechaChanged();
        /// <summary>
        /// There are no comments for Property DocCur in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DocCur
        {
            get
            {
                return this._DocCur;
            }
            set
            {
                this.OnDocCurChanging(value);
                this._DocCur = value;
                this.OnDocCurChanged();
                this.OnPropertyChanged("DocCur");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DocCur;
        partial void OnDocCurChanging(string value);
        partial void OnDocCurChanged();
        /// <summary>
        /// There are no comments for Property ItemCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ItemCode
        {
            get
            {
                return this._ItemCode;
            }
            set
            {
                this.OnItemCodeChanging(value);
                this._ItemCode = value;
                this.OnItemCodeChanged();
                this.OnPropertyChanged("ItemCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ItemCode;
        partial void OnItemCodeChanging(string value);
        partial void OnItemCodeChanged();
        /// <summary>
        /// There are no comments for Property Dscription in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Dscription
        {
            get
            {
                return this._Dscription;
            }
            set
            {
                this.OnDscriptionChanging(value);
                this._Dscription = value;
                this.OnDscriptionChanged();
                this.OnPropertyChanged("Dscription");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Dscription;
        partial void OnDscriptionChanging(string value);
        partial void OnDscriptionChanged();
        /// <summary>
        /// There are no comments for Property SlpName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SlpName
        {
            get
            {
                return this._SlpName;
            }
            set
            {
                this.OnSlpNameChanging(value);
                this._SlpName = value;
                this.OnSlpNameChanged();
                this.OnPropertyChanged("SlpName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SlpName;
        partial void OnSlpNameChanging(string value);
        partial void OnSlpNameChanged();
        /// <summary>
        /// There are no comments for Property SlpCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> SlpCode
        {
            get
            {
                return this._SlpCode;
            }
            set
            {
                this.OnSlpCodeChanging(value);
                this._SlpCode = value;
                this.OnSlpCodeChanged();
                this.OnPropertyChanged("SlpCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _SlpCode;
        partial void OnSlpCodeChanging(global::System.Nullable<int> value);
        partial void OnSlpCodeChanged();
        /// <summary>
        /// There are no comments for Property OcrCode3ST in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string OcrCode3ST
        {
            get
            {
                return this._OcrCode3ST;
            }
            set
            {
                this.OnOcrCode3STChanging(value);
                this._OcrCode3ST = value;
                this.OnOcrCode3STChanged();
                this.OnPropertyChanged("OcrCode3ST");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _OcrCode3ST;
        partial void OnOcrCode3STChanging(string value);
        partial void OnOcrCode3STChanged();
        /// <summary>
        /// There are no comments for Property OcrCode2ST in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string OcrCode2ST
        {
            get
            {
                return this._OcrCode2ST;
            }
            set
            {
                this.OnOcrCode2STChanging(value);
                this._OcrCode2ST = value;
                this.OnOcrCode2STChanged();
                this.OnPropertyChanged("OcrCode2ST");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _OcrCode2ST;
        partial void OnOcrCode2STChanging(string value);
        partial void OnOcrCode2STChanged();
        /// <summary>
        /// There are no comments for Property OcrCodeST in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string OcrCodeST
        {
            get
            {
                return this._OcrCodeST;
            }
            set
            {
                this.OnOcrCodeSTChanging(value);
                this._OcrCodeST = value;
                this.OnOcrCodeSTChanged();
                this.OnPropertyChanged("OcrCodeST");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _OcrCodeST;
        partial void OnOcrCodeSTChanging(string value);
        partial void OnOcrCodeSTChanged();
        /// <summary>
        /// There are no comments for Property Documento in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Documento
        {
            get
            {
                return this._Documento;
            }
            set
            {
                this.OnDocumentoChanging(value);
                this._Documento = value;
                this.OnDocumentoChanged();
                this.OnPropertyChanged("Documento");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Documento;
        partial void OnDocumentoChanging(string value);
        partial void OnDocumentoChanged();
        /// <summary>
        /// There are no comments for Property Quantity in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> Quantity
        {
            get
            {
                return this._Quantity;
            }
            set
            {
                this.OnQuantityChanging(value);
                this._Quantity = value;
                this.OnQuantityChanged();
                this.OnPropertyChanged("Quantity");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _Quantity;
        partial void OnQuantityChanging(global::System.Nullable<decimal> value);
        partial void OnQuantityChanged();
        /// <summary>
        /// There are no comments for Property TotalCosto in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> TotalCosto
        {
            get
            {
                return this._TotalCosto;
            }
            set
            {
                this.OnTotalCostoChanging(value);
                this._TotalCosto = value;
                this.OnTotalCostoChanged();
                this.OnPropertyChanged("TotalCosto");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _TotalCosto;
        partial void OnTotalCostoChanging(global::System.Nullable<decimal> value);
        partial void OnTotalCostoChanged();
        /// <summary>
        /// There are no comments for Property TotalVenta in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> TotalVenta
        {
            get
            {
                return this._TotalVenta;
            }
            set
            {
                this.OnTotalVentaChanging(value);
                this._TotalVenta = value;
                this.OnTotalVentaChanged();
                this.OnPropertyChanged("TotalVenta");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _TotalVenta;
        partial void OnTotalVentaChanging(global::System.Nullable<decimal> value);
        partial void OnTotalVentaChanged();
        /// <summary>
        /// There are no comments for Property Price in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> Price
        {
            get
            {
                return this._Price;
            }
            set
            {
                this.OnPriceChanging(value);
                this._Price = value;
                this.OnPriceChanged();
                this.OnPropertyChanged("Price");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _Price;
        partial void OnPriceChanging(global::System.Nullable<decimal> value);
        partial void OnPriceChanged();
        /// <summary>
        /// There are no comments for Property Costo in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> Costo
        {
            get
            {
                return this._Costo;
            }
            set
            {
                this.OnCostoChanging(value);
                this._Costo = value;
                this.OnCostoChanged();
                this.OnPropertyChanged("Costo");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _Costo;
        partial void OnCostoChanging(global::System.Nullable<decimal> value);
        partial void OnCostoChanged();
        /// <summary>
        /// There are no comments for Property Margen in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> Margen
        {
            get
            {
                return this._Margen;
            }
            set
            {
                this.OnMargenChanging(value);
                this._Margen = value;
                this.OnMargenChanged();
                this.OnPropertyChanged("Margen");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _Margen;
        partial void OnMargenChanging(global::System.Nullable<decimal> value);
        partial void OnMargenChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for MSS_REPORTES.services.ventas.ventasServices.ventasSolesType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// DocEntry
    /// LineNum
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("ventasSoles")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("DocEntry", "LineNum")]
    public partial class ventasSolesType : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ventasSolesType object.
        /// </summary>
        /// <param name="docEntry">Initial value of DocEntry.</param>
        /// <param name="lineNum">Initial value of LineNum.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ventasSolesType CreateventasSolesType(int docEntry, int lineNum)
        {
            ventasSolesType ventasSolesType = new ventasSolesType();
            ventasSolesType.DocEntry = docEntry;
            ventasSolesType.LineNum = lineNum;
            return ventasSolesType;
        }
        /// <summary>
        /// There are no comments for Property DocEntry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int DocEntry
        {
            get
            {
                return this._DocEntry;
            }
            set
            {
                this.OnDocEntryChanging(value);
                this._DocEntry = value;
                this.OnDocEntryChanged();
                this.OnPropertyChanged("DocEntry");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _DocEntry;
        partial void OnDocEntryChanging(int value);
        partial void OnDocEntryChanged();
        /// <summary>
        /// There are no comments for Property DocNum in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> DocNum
        {
            get
            {
                return this._DocNum;
            }
            set
            {
                this.OnDocNumChanging(value);
                this._DocNum = value;
                this.OnDocNumChanged();
                this.OnPropertyChanged("DocNum");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _DocNum;
        partial void OnDocNumChanging(global::System.Nullable<int> value);
        partial void OnDocNumChanged();
        /// <summary>
        /// There are no comments for Property LineNum in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int LineNum
        {
            get
            {
                return this._LineNum;
            }
            set
            {
                this.OnLineNumChanging(value);
                this._LineNum = value;
                this.OnLineNumChanged();
                this.OnPropertyChanged("LineNum");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _LineNum;
        partial void OnLineNumChanging(int value);
        partial void OnLineNumChanged();
        /// <summary>
        /// There are no comments for Property CardCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CardCode
        {
            get
            {
                return this._CardCode;
            }
            set
            {
                this.OnCardCodeChanging(value);
                this._CardCode = value;
                this.OnCardCodeChanged();
                this.OnPropertyChanged("CardCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CardCode;
        partial void OnCardCodeChanging(string value);
        partial void OnCardCodeChanged();
        /// <summary>
        /// There are no comments for Property CardName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CardName
        {
            get
            {
                return this._CardName;
            }
            set
            {
                this.OnCardNameChanging(value);
                this._CardName = value;
                this.OnCardNameChanged();
                this.OnPropertyChanged("CardName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CardName;
        partial void OnCardNameChanging(string value);
        partial void OnCardNameChanged();
        /// <summary>
        /// There are no comments for Property Sucursal in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Sucursal
        {
            get
            {
                return this._Sucursal;
            }
            set
            {
                this.OnSucursalChanging(value);
                this._Sucursal = value;
                this.OnSucursalChanged();
                this.OnPropertyChanged("Sucursal");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Sucursal;
        partial void OnSucursalChanging(string value);
        partial void OnSucursalChanged();
        /// <summary>
        /// There are no comments for Property Fecha in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> Fecha
        {
            get
            {
                return this._Fecha;
            }
            set
            {
                this.OnFechaChanging(value);
                this._Fecha = value;
                this.OnFechaChanged();
                this.OnPropertyChanged("Fecha");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _Fecha;
        partial void OnFechaChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnFechaChanged();
        /// <summary>
        /// There are no comments for Property DocCur in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DocCur
        {
            get
            {
                return this._DocCur;
            }
            set
            {
                this.OnDocCurChanging(value);
                this._DocCur = value;
                this.OnDocCurChanged();
                this.OnPropertyChanged("DocCur");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DocCur;
        partial void OnDocCurChanging(string value);
        partial void OnDocCurChanged();
        /// <summary>
        /// There are no comments for Property ItemCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ItemCode
        {
            get
            {
                return this._ItemCode;
            }
            set
            {
                this.OnItemCodeChanging(value);
                this._ItemCode = value;
                this.OnItemCodeChanged();
                this.OnPropertyChanged("ItemCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ItemCode;
        partial void OnItemCodeChanging(string value);
        partial void OnItemCodeChanged();
        /// <summary>
        /// There are no comments for Property Dscription in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Dscription
        {
            get
            {
                return this._Dscription;
            }
            set
            {
                this.OnDscriptionChanging(value);
                this._Dscription = value;
                this.OnDscriptionChanged();
                this.OnPropertyChanged("Dscription");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Dscription;
        partial void OnDscriptionChanging(string value);
        partial void OnDscriptionChanged();
        /// <summary>
        /// There are no comments for Property SlpName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SlpName
        {
            get
            {
                return this._SlpName;
            }
            set
            {
                this.OnSlpNameChanging(value);
                this._SlpName = value;
                this.OnSlpNameChanged();
                this.OnPropertyChanged("SlpName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SlpName;
        partial void OnSlpNameChanging(string value);
        partial void OnSlpNameChanged();
        /// <summary>
        /// There are no comments for Property SlpCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> SlpCode
        {
            get
            {
                return this._SlpCode;
            }
            set
            {
                this.OnSlpCodeChanging(value);
                this._SlpCode = value;
                this.OnSlpCodeChanged();
                this.OnPropertyChanged("SlpCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _SlpCode;
        partial void OnSlpCodeChanging(global::System.Nullable<int> value);
        partial void OnSlpCodeChanged();
        /// <summary>
        /// There are no comments for Property OcrCodeST in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string OcrCodeST
        {
            get
            {
                return this._OcrCodeST;
            }
            set
            {
                this.OnOcrCodeSTChanging(value);
                this._OcrCodeST = value;
                this.OnOcrCodeSTChanged();
                this.OnPropertyChanged("OcrCodeST");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _OcrCodeST;
        partial void OnOcrCodeSTChanging(string value);
        partial void OnOcrCodeSTChanged();
        /// <summary>
        /// There are no comments for Property OcrCode2ST in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string OcrCode2ST
        {
            get
            {
                return this._OcrCode2ST;
            }
            set
            {
                this.OnOcrCode2STChanging(value);
                this._OcrCode2ST = value;
                this.OnOcrCode2STChanged();
                this.OnPropertyChanged("OcrCode2ST");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _OcrCode2ST;
        partial void OnOcrCode2STChanging(string value);
        partial void OnOcrCode2STChanged();
        /// <summary>
        /// There are no comments for Property OcrCode3ST in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string OcrCode3ST
        {
            get
            {
                return this._OcrCode3ST;
            }
            set
            {
                this.OnOcrCode3STChanging(value);
                this._OcrCode3ST = value;
                this.OnOcrCode3STChanged();
                this.OnPropertyChanged("OcrCode3ST");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _OcrCode3ST;
        partial void OnOcrCode3STChanging(string value);
        partial void OnOcrCode3STChanged();
        /// <summary>
        /// There are no comments for Property Documento in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Documento
        {
            get
            {
                return this._Documento;
            }
            set
            {
                this.OnDocumentoChanging(value);
                this._Documento = value;
                this.OnDocumentoChanged();
                this.OnPropertyChanged("Documento");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Documento;
        partial void OnDocumentoChanging(string value);
        partial void OnDocumentoChanged();
        /// <summary>
        /// There are no comments for Property Quantity in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> Quantity
        {
            get
            {
                return this._Quantity;
            }
            set
            {
                this.OnQuantityChanging(value);
                this._Quantity = value;
                this.OnQuantityChanged();
                this.OnPropertyChanged("Quantity");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _Quantity;
        partial void OnQuantityChanging(global::System.Nullable<decimal> value);
        partial void OnQuantityChanged();
        /// <summary>
        /// There are no comments for Property TotalCosto in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> TotalCosto
        {
            get
            {
                return this._TotalCosto;
            }
            set
            {
                this.OnTotalCostoChanging(value);
                this._TotalCosto = value;
                this.OnTotalCostoChanged();
                this.OnPropertyChanged("TotalCosto");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _TotalCosto;
        partial void OnTotalCostoChanging(global::System.Nullable<decimal> value);
        partial void OnTotalCostoChanged();
        /// <summary>
        /// There are no comments for Property TotalVenta in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> TotalVenta
        {
            get
            {
                return this._TotalVenta;
            }
            set
            {
                this.OnTotalVentaChanging(value);
                this._TotalVenta = value;
                this.OnTotalVentaChanged();
                this.OnPropertyChanged("TotalVenta");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _TotalVenta;
        partial void OnTotalVentaChanging(global::System.Nullable<decimal> value);
        partial void OnTotalVentaChanged();
        /// <summary>
        /// There are no comments for Property Price in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> Price
        {
            get
            {
                return this._Price;
            }
            set
            {
                this.OnPriceChanging(value);
                this._Price = value;
                this.OnPriceChanged();
                this.OnPropertyChanged("Price");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _Price;
        partial void OnPriceChanging(global::System.Nullable<decimal> value);
        partial void OnPriceChanged();
        /// <summary>
        /// There are no comments for Property Costo in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> Costo
        {
            get
            {
                return this._Costo;
            }
            set
            {
                this.OnCostoChanging(value);
                this._Costo = value;
                this.OnCostoChanged();
                this.OnPropertyChanged("Costo");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _Costo;
        partial void OnCostoChanging(global::System.Nullable<decimal> value);
        partial void OnCostoChanged();
        /// <summary>
        /// There are no comments for Property Margen in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> Margen
        {
            get
            {
                return this._Margen;
            }
            set
            {
                this.OnMargenChanging(value);
                this._Margen = value;
                this.OnMargenChanged();
                this.OnPropertyChanged("Margen");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _Margen;
        partial void OnMargenChanging(global::System.Nullable<decimal> value);
        partial void OnMargenChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for MSS_REPORTES.services.ventas.ventasServices.vendedoresType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// SlpCode
    /// SlpName
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("vendedores")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("SlpCode", "SlpName")]
    public partial class vendedoresType : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new vendedoresType object.
        /// </summary>
        /// <param name="slpCode">Initial value of SlpCode.</param>
        /// <param name="slpName">Initial value of SlpName.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static vendedoresType CreatevendedoresType(int slpCode, string slpName)
        {
            vendedoresType vendedoresType = new vendedoresType();
            vendedoresType.SlpCode = slpCode;
            vendedoresType.SlpName = slpName;
            return vendedoresType;
        }
        /// <summary>
        /// There are no comments for Property SlpCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int SlpCode
        {
            get
            {
                return this._SlpCode;
            }
            set
            {
                this.OnSlpCodeChanging(value);
                this._SlpCode = value;
                this.OnSlpCodeChanged();
                this.OnPropertyChanged("SlpCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _SlpCode;
        partial void OnSlpCodeChanging(int value);
        partial void OnSlpCodeChanged();
        /// <summary>
        /// There are no comments for Property SlpName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SlpName
        {
            get
            {
                return this._SlpName;
            }
            set
            {
                this.OnSlpNameChanging(value);
                this._SlpName = value;
                this.OnSlpNameChanged();
                this.OnPropertyChanged("SlpName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SlpName;
        partial void OnSlpNameChanging(string value);
        partial void OnSlpNameChanged();
        /// <summary>
        /// There are no comments for Property CodigoNombre in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CodigoNombre
        {
            get
            {
                return this._CodigoNombre;
            }
            set
            {
                this.OnCodigoNombreChanging(value);
                this._CodigoNombre = value;
                this.OnCodigoNombreChanged();
                this.OnPropertyChanged("CodigoNombre");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CodigoNombre;
        partial void OnCodigoNombreChanging(string value);
        partial void OnCodigoNombreChanged();
        /// <summary>
        /// There are no comments for Property Active in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Active
        {
            get
            {
                return this._Active;
            }
            set
            {
                this.OnActiveChanging(value);
                this._Active = value;
                this.OnActiveChanged();
                this.OnPropertyChanged("Active");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Active;
        partial void OnActiveChanging(string value);
        partial void OnActiveChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for MSS_REPORTES.services.ventas.ventasServices.articuloType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ItemCode
    /// ItemName
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("articulo")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ItemCode", "ItemName")]
    public partial class articuloType : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new articuloType object.
        /// </summary>
        /// <param name="itemCode">Initial value of ItemCode.</param>
        /// <param name="itemName">Initial value of ItemName.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static articuloType CreatearticuloType(string itemCode, string itemName)
        {
            articuloType articuloType = new articuloType();
            articuloType.ItemCode = itemCode;
            articuloType.ItemName = itemName;
            return articuloType;
        }
        /// <summary>
        /// There are no comments for Property ItemCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ItemCode
        {
            get
            {
                return this._ItemCode;
            }
            set
            {
                this.OnItemCodeChanging(value);
                this._ItemCode = value;
                this.OnItemCodeChanged();
                this.OnPropertyChanged("ItemCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ItemCode;
        partial void OnItemCodeChanging(string value);
        partial void OnItemCodeChanged();
        /// <summary>
        /// There are no comments for Property ItemName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ItemName
        {
            get
            {
                return this._ItemName;
            }
            set
            {
                this.OnItemNameChanging(value);
                this._ItemName = value;
                this.OnItemNameChanged();
                this.OnPropertyChanged("ItemName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ItemName;
        partial void OnItemNameChanging(string value);
        partial void OnItemNameChanged();
        /// <summary>
        /// There are no comments for Property OnHand in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> OnHand
        {
            get
            {
                return this._OnHand;
            }
            set
            {
                this.OnOnHandChanging(value);
                this._OnHand = value;
                this.OnOnHandChanged();
                this.OnPropertyChanged("OnHand");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _OnHand;
        partial void OnOnHandChanging(global::System.Nullable<decimal> value);
        partial void OnOnHandChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for MSS_REPORTES.services.ventas.ventasServices.clienteType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CardCode
    /// CardName
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("cliente")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("CardCode", "CardName")]
    public partial class clienteType : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new clienteType object.
        /// </summary>
        /// <param name="cardCode">Initial value of CardCode.</param>
        /// <param name="cardName">Initial value of CardName.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static clienteType CreateclienteType(string cardCode, string cardName)
        {
            clienteType clienteType = new clienteType();
            clienteType.CardCode = cardCode;
            clienteType.CardName = cardName;
            return clienteType;
        }
        /// <summary>
        /// There are no comments for Property CardCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CardCode
        {
            get
            {
                return this._CardCode;
            }
            set
            {
                this.OnCardCodeChanging(value);
                this._CardCode = value;
                this.OnCardCodeChanged();
                this.OnPropertyChanged("CardCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CardCode;
        partial void OnCardCodeChanging(string value);
        partial void OnCardCodeChanged();
        /// <summary>
        /// There are no comments for Property CardName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CardName
        {
            get
            {
                return this._CardName;
            }
            set
            {
                this.OnCardNameChanging(value);
                this._CardName = value;
                this.OnCardNameChanged();
                this.OnPropertyChanged("CardName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CardName;
        partial void OnCardNameChanging(string value);
        partial void OnCardNameChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
